# Generated by Django 4.1.6 on 2023-02-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0004_gamemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='game_string',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='is_palindrome',
            field=models.BooleanField(default=False),
        ),
    ]
